### ISSUE TITLE
cant clone

### ISSUE THREAD

**Issue by drachedachte1** [Rakambda/ChannelPointsMiner#364]
### Description

![image](https://user-images.githubusercontent.com/65346683/204242784-973d9b6c-1600-48d1-ba4f-cf61d023d1f1.png)

### Version / commit

2.0.0

### Relevant log output

```shell
Cloning into 'ChannelPointsMiner'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Rakambda** [comment]
This isn't an issue with the miner.

You probably never set a ssh key for your git account ?
Just try with the https method.

https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository?tool=webui
