### ISSUE TITLE
Drops not being claimed

### ISSUE THREAD

**Issue by nexus667** [Rakambda/ChannelPointsMiner#450]
### Description

Twitch made some change and drops are no longer claimed.  This changes has also broken a chrome extension Automatic Twitch.  I don't know if these are the errors but the stream would have been from 6-8:30pm. Running with 3 accounts.  I manually claimed on 2 of the accounts.

<img width="719" alt="image" src="https://user-images.githubusercontent.com/31312585/222749432-25a84c79-7af1-4c82-b5ee-7ae5048cf04d.png">

### Version / commit

2.2.1

### Relevant log output

```shell
Errors:

18:13:51,015 ERROR [pool-2-thread-2] f.r.c.m.a.g.g.GQLApi {account_name=m7755} - Received GQL error response: [GQLError(message=PersistedQueryNotFound, locations=[], path=[])]
18:13:53,337 ERROR [pool-4-thread-4] f.r.c.m.a.g.g.GQLApi {account_name=sw667} - Received GQL error response: [GQLError(message=PersistedQueryNotFound, locations=[], path=[])]
18:13:53,930 ERROR [pool-6-thread-1] f.r.c.m.a.g.g.GQLApi {account_name=dt34565} - Received GQL error response: [GQLError(message=PersistedQueryNotFound, locations=[], path=[])]
```

**Comment by Rakambda** [comment]
You're not running version 2.2.1, if it was the xase the log would be different (https://github.com/Rakambda/ChannelPointsMiner/blob/2.2.1/miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApi.java#L112)

Your version is before 2.2.0

**Comment by nexus667** [comment]
Where do I get the version from?

I did a git pull yesterday before the run.

**Comment by nexus667** [comment]
Is there a way to check the version?

ran the gradlew build -x test and re-ran the jar. It collected the past drop but did not show that it was claimed and had the following error messages:

18:41:11,701 INFO [pool-3-thread-1] f.r.c.m.l.LoggerEventListener {account_name=mt5} - Drop available [Prime Time 339]
18:41:11,903 ERROR [pool-2-thread-4] f.r.c.m.l.UnirestLogger {account_name=mt5} - Failed to request https://gql.twitch.tv/gql got statusCode `200` and parsing error: Optional[kong.unirest.core.UnirestParsingException: kong.unirest.core.UnirestException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "dropType" (class fr.rakambda.channelpointsminer.miner.api.gql.gql.data.types.ClaimDropRewardsPayload), not marked as ignorable (2 known properties: "isUserAccountConnected", "status"])
 at [Source: (String)"{"data":{"claimDropRewards":{"status":"ELIGIBLE_FOR_ALL","isUserAccountConnected":true,"dropType":{"id":"009cbb0c-fc31-4f59-a2f9-8afa27304f4a","campaign":{"id":"3ae36c53-27b5-43b0-bc66-895996122f94","detailsURL":"https://forums.warf.com/topic/1341-community-stream-schedule-february-27-march-3/","__typename":"DropCampaign"},"__typename":"TimeBasedDrop"},"__typename":"ClaimDropRewardsPayload"}},"extensions":{"durationMilliseconds":44,"operationName":"DropsPage_ClaimDropRewards","requestID":"[truncated 30 chars]; line: 1, column: 401] (through reference chain: fr.rakambda.channelpointsminer.miner.api.gql.gql.data.GQLResponse["data"]->fr.rakambda.channelpointsminer.miner.api.gql.gql.data.dropspageclaimdroprewards.DropsPageClaimDropRewardsData["claimDropRewards"]->fr.rakambda.channelpointsminer.miner.api.gql.gql.data.types.ClaimDropRewardsPayload["dropType"])]
18:41:11,904 ERROR [pool-2-thread-4] f.r.c.m.l.UnirestLogger {account_name=mt5} - Failed to parse body: {"data":{"claimDropRewards":{"status":"ELIGIBLE_FOR_ALL","isUserAccountConnected":true,"dropType":{"id":"009cbb0c-fc31-4f59-a2f9-8afa27304f4a","campaign":{"id":"3ae36c53-27b5-43b0-bc66-895996122f94","detailsURL":"https://forums.warf.com/topic/1341-community-stream-schedule-february-27-march-3/","__typename":"DropCampaign"},"__typename":"TimeBasedDrop"},"__typename":"ClaimDropRewardsPayload"}},"extensions":{"durationMilliseconds":44,"operationName":"DropsPage_ClaimDropRewards","requestID":"01GTM90GJ3QFHHFDE"}}

**Comment by Rakambda** [comment]
Version is displayed in the logs at the beginning.

For the error log, try with this build: https://github.com/Rakambda/ChannelPointsMiner/actions/runs/4326311063
