### ISSUE TITLE
Drops not being claimed

### ISSUE THREAD

**Issue by Messiah93** [Rakambda/ChannelPointsMiner#464]
### Description

Hello, i'm facing a little bug:

ChannelPointsMiner version: 2.2.1 (from release repo)
Config: "participateCampaigns":true,

Drops are mined, but not claimed... Every 15 minutes, it print in console "Drop available" but it's not claiming. 

Thank's.

### Version / commit

2.2.1 | 8473d9d | HEAD

### Relevant log output

```shell
[32m21:31:46,403 INFO [pool-3-thread-440] f.r.c.m.l.LoggerEventListener {account_name=xxx} - Drop available [Omen Cannons][m
[1;31m21:31:46,603 ERROR [pool-2-thread-2] f.r.c.m.a.g.g.GQLApi {account_name=xxx} - Received GQL error response for DropsPage_ClaimDropRewards: [GQLError(message=PersistedQueryNotFound, locations=[], path=[])][m
```

**Comment by Rakambda** [comment]
I think I have a modification on the develop branch that may fix that issue. Can you try with this version ans see if it fixes your issue ?
I use the develop branch daily and didn't see your issue so I'd guess it'd help. If so I'll make a release of it.

**Comment by Messiah93** [comment]
I downloaded it and I'm testing this version, I'll let you know ASAP, thank you.

**Comment by Messiah93** [comment]
Yep, it claim drops with 2.2.2 | 1fe5786 | develop

[32m21:09:27,542 INFO [pool-3-thread-63] f.r.c.m.l.LoggerEventListener {account_name=xxx} - Drop available [Marble Day 87 - Drop 2][m
[32m21:09:27,767 INFO [pool-3-thread-63] f.r.c.m.l.LoggerEventListener {account_name=xxx} - Drop claimed [Marble Day 87 - Drop 2][m
