### ISSUE TITLE
Add priorities

### ISSUE THREAD

**Issue by Messiah93** [Rakambda/ChannelPointsMiner#516]
### Description

Hey, I think that would be cool to add priorities for moments and trains of the hype If it's possible.

**Comment by Rakambda** [comment]
For moments I'm not sure what would be the purpose of it. Moments are still claimed even if the streamer isn't being watched. Watching just grants you the viewing channel points, but everything that is more based on "events" still works (raids, moments).

For hype trains too, what's the purpose? I don't think that when a train happens you get any points from it by just watching?

**Comment by Messiah93** [comment]
Yes... True.
