### ISSUE TITLE
Linux: Creating log file named "/logs/miner.log" at the home user root.

### ISSUE THREAD

**Issue by Messiah93** [Rakambda/ChannelPointsMiner#571]
### Description

When I start /home/m93_srv7_u2/service_cpm1/miner-shaded.jar, this create a folder named "logs" at the home user root (/home/m93_srv7_u2/logs), and in this logs folder is created at the same time a file "miner.log", which remains empty by the way. 

I think the folder may be located at /home/m93_srv7_u2/service_cpm1 instead of /home/m93_srv7_u2/

Start file is located at /home/m93_srv7_u2/service_cpm1/run.sh and the content is:

```
java -jar miner-shaded.jar --settings config.json
```

I try to add "export HOME=$PWD" at top of start file but it didn't change anything. 

Does it exist a workaround for the file stops being created at the root of the user home?

### Version / commit

2.2.6 | 3e83c06 | HEAD

**Comment by Rakambda** [comment]
You can define your own logger file that'll log just to the console or put it in the path you desire.

* https://rakambda.github.io/ChannelPointsMiner/miner/main/installation/clone.html
* https://rakambda.github.io/ChannelPointsMiner/miner/main/configuration/logger.html
* https://github.com/Rakambda/ChannelPointsMiner/tree/develop/src/examples/loggers

**Comment by Messiah93** [comment]
I don't want to use any logger because i'm logging from tmux instance directly, and i'm using Discord Webhook. I just want to avoid folder and file logs/miner.log from be created if it's possible.

**Comment by couchoud-t** [comment]
What's the issue with using a custom logger?
You can pretty much define a logger that does nothing or log to console, basically "avoid folder and file logs/miner.log from be created".

**Comment by Messiah93** [comment]
Yep it working with console only logger, but I thought by default no miner.log was generated, especially it's not in the right place and empty by default.

**Comment by couchoud-t** [comment]
I changed the default location in the develop branch d31599cac980921b2b696419b2b15bd8e8b46b48. Will be released along some other stuff as it's not super critical.
